using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using com.LoanTek.Quoting;
using LoanTek.Pricing.BusinessObjects;
using LoanTek.Utilities;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.Web.Http.Description;
using com.LoanTek.Types;

namespace com.LoanTek.API.Requests
{
    /// <summary>
    /// Default Quote object used for Common Mortgage responses.
    /// </summary>
    /// <remarks>
    /// Overwrites the com.LoanTek.Quoting.Common.Quote object, removing or 'hiding' unneeded properties. 
    /// </remarks>
    public class MortgageLoanQuote : Quoting.Common.Quote
    {
        public MortgageLoanQuote() { }

        public MortgageLoanQuote(IQuote x)
        {
            ClassMappingUtilities.SetPropertiesForTarget(x, this);
            if (string.IsNullOrEmpty(this.QuoteId))
                this.QuoteId = x.Id.ToString();
        }
        [XmlIgnore][JsonIgnore][IgnoreDataMember] public override int LeadGenerationMethodTypeId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override string ClientDefinedIdentifier { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override long Id { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override long ParentId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override string RawRequest { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override string RawResponse { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override string HiddenAdjustments { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override List<AAdjustment> HiddenAdjustmentList { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public new bool HasStopEncountered { get; set; }

        #region Internal Fields

        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int BranchId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int ChannelProductId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int CompUserBranchId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int CompUserId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int UserId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override DateTime RSVersionDate { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int RSLenderId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int RSMasterId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int RSMasterLoanProgramId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override long RSRateCellId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int RSRateId { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int RSVersion { get; set; }
        [XmlIgnore] [JsonIgnore] [IgnoreDataMember] public override int RSVersionId { get; set; }

        #endregion

        //[XmlIgnore] [JsonIgnore] public override string ExternalLink { get; set; }

        /// <summary>
        /// Unique Id generated by LoanTek for this Quote. 
        /// </summary>
        //[Required]
        //public new string QuoteId { get; set; }
    }
}