//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.LoanTek.API.Leads.Clients.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sqllb.loantek.com;Initial Catalog=LoanTek;Persist Security Info=True;" +
            "User ID=sa;Password=!MANTLE7")]
        public string DataContextLoanTekWrite {
            get {
                return ((string)(this["DataContextLoanTekWrite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sqllb.loantek.com;Initial Catalog=LoanTek;Persist Security Info=True;" +
            "User ID=sa;Password=!MANTLE7;ApplicationIntent=ReadOnly")]
        public string DataContextLoanTekRead {
            get {
                return ((string)(this["DataContextLoanTekRead"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sqllb.loantek.com;Initial Catalog=Leads;Persist Security Info=True;Us" +
            "er ID=sa;Password=!MANTLE7")]
        public string DataContextLeadsWrite {
            get {
                return ((string)(this["DataContextLeadsWrite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sqllb.loantek.com;Initial Catalog=Leads;Persist Security Info=True;Us" +
            "er ID=sa;Password=!MANTLE7;ApplicationIntent=ReadOnly")]
        public string DataContextLeadsRead {
            get {
                return ((string)(this["DataContextLeadsRead"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sqllb.loantek.com;Initial Catalog=Bankrate;Persist Security Info=True" +
            ";User ID=sa;Password=!MANTLE7;ApplicationIntent=ReadOnly")]
        public string DataContextBankrateRead {
            get {
                return ((string)(this["DataContextBankrateRead"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sqllb.loantek.com;Initial Catalog=Bankrate;Persist Security Info=True" +
            ";User ID=sa;Password=!MANTLE7")]
        public string DataContextBankrateWrite {
            get {
                return ((string)(this["DataContextBankrateWrite"]));
            }
        }
    }
}
